//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MySETIviewer.rc
//
#define IDS_APP_TITLE                   104
#define IDD_ABOUTBOX                    105
#define IDM_ABOUT                       106
#define IDM_EXIT                        108
#define IDI_MYSETIVIEWER                110
#define IDC_MYSETIVIEWER                112
#define IDR_MAINFRAME                   128
#define IDD_SETTINGS_DISPLAY            134
#define IDD_BITTOOLS_BINARYIMAGE        136
#define IDD_DISPLAY                     137
#define IDD_SETTINGS_LAYERS             138
#define IDD_SETTINGS_GLOBAL             139
#define IDD_IMAGE                       140
#define IDD_BITTOOLS_TEXT2STREAM        158
#define IDC_IMAGE_OUTPUT                1079
#define IDC_IMAGE_OUTPUT_BROWSE         1080
#define IDC_GENERATE_BMP                1081
#define IDC_BMP_RESULTS_BROWSE          1082
#define IDC_IMG_TEMP                    1083
#define IDC_IMG_TEMP_BROWSE             1084
#define IDC_BMP_RESULTS                 1085
#define IDC_BACKGROUND_COLOR            1086
#define IDC_ABOUT_AUTHOR                1087
#define IDC_APPLY                       1088
#define IDC_SCALE_RESET                 1089
#define IDC_ABOUT_LICENSE               1090
#define IDC_FILESIZE                    1090
#define IDC_GAP_MAJOR_COLOR             1091
#define IDC_ABOUT_VERSION               1092
#define IDC_GAP_MINOR_COLOR             1093
#define IDC_POS_RESET                   1095
#define IDC_CONVERT                     1100
#define IDC_ABOUT_NAME                  1101
#define IDC_XSIZE                       1102
#define IDC_ABOUT_COPYRIGHT             1111
#define IDC_SETTINGS_AUTO_PNG           1114
#define IDC_SETTINGS_START_LAST         1115
#define IDC_GRID_ENABLE                 1116
#define IDC_SETTINGS_ENABLE_GAP         1118
#define IDC_GAP_ENABLE                  1119
#define IDC_INI_FILE                    1120
#define IDC_EXE_FILE                    1121
#define IDC_BLOCK_BITS                  1127
#define IDC_BLOCK_NUM                   1129
#define IDC_BIT_DEPTH                   1131
#define IDC_TEXT_INPUT                  1138
#define IDC_BINARY_INPUT                1159
#define IDC_PROLOGUE_SIZE               1161
#define IDC_BLOCK_HEADER_BITS           1163
#define IDC_INPUT_BROWSE                1164
#define IDC_BINARY_OUTPUT               1167
#define IDC_BITORDER                    1168
#define IDC_INPUT_BITORDER              1169
#define IDC_OUTPUT_BROWSE               1170
#define IDC_SCALE_PIXEL                 1171
#define IDC_INVERT                      1173
#define IDC_XSIZE_END                   1175
#define IDC_COMBO_LAYER_LIST            1183
#define IDC_GRID_X_MAJOR                1200
#define IDC_GRID_X_MINOR                1201
#define IDC_GRID_Y_MAJOR                1202
#define IDC_GRID_Y_MINOR                1203
#define IDC_GAP_X_MAJOR                 1204
#define IDC_GAP_X_MINOR                 1205
#define IDC_GAP_Y_MAJOR                 1206
#define IDC_GAP_Y_MINOR                 1207
#define IDC_BACKGROUND                  1208
#define IDC_GAP_MINOR                   1209
#define IDC_GAP_MAJOR                   1210
#define IDC_LAYER_COLOR                 1211
#define IDC_X_MINUS                     1212
#define IDC_X_PLUS                      1213
#define IDC_X_POS                       1214
#define IDC_Y_POS                       1215
#define IDC_Y_MINUS                     1216
#define IDC_Y_PLUS                      1217
#define IDC_SELECT_LAYER_COLOR          1218
#define IDC_SELECT_BACKGROUND_COLOR     1219
#define IDC_DEFAULT_COLOR               1220
#define IDC_LAYER_LIST                  1221
#define IDC_DELETE_LAYER                1222
#define IDC_SELECT_OVERLAY_COLOR        1223
#define IDC_OVERLAY_COLOR               1224
#define IDC_ENABLE                      1225
#define IDC_LAYERS_MIN_X                1226
#define IDC_LAYER_TEXT                  1227
#define IDC_GLOBAL_YPOS_UP              1227
#define IDC_LAYERS_MIN_Y                1228
#define IDC_RADIO2                      1228
#define IDC_GLOBAL_YPOS_DOWN            1228
#define IDM_PROPERTIES_SETTINGS         32601
#define IDM_SETTINGS                    32602
#define IDC_FILE_OPEN                   32604
#define IDM_SETTINGS_LAYERS             32609
#define IDM_SETTINGS_DISPLAY            32610
#define IDM_ADD_LAYER                   32611
#define ID_LAYER_REMOVELAYER            32612
#define IDM_REMOVE_LAYER                32613
#define ID_LAYER_SAVELAYERCONFIGURATION 32614
#define ID_LAYER_LOADLAYERCONFIGURATION 32615
#define IDM_SAVE_CONFIGURATION          32616
#define IDM_LOAD_CONFIGURATION          32617
#define ID_LAYER_RELOADALLLAYERS        32618
#define IDM_RELOAD_LAYERS               32619
#define ID_LAYER_SAVELAYERCONFIGURATIONAS 32620
#define IDM_SAVE_AS_CONFIGURATION       32621
#define ID_SETTINGS_GLOBAL              32622
#define IDM_SETTINGS_GLOBAL             32623
#define ID_LAYER_NEW                    32624
#define IDM_LAYER_NEW                   32625
#define ID_LAYER_SAVEIMAGEASBMPFILE     32626
#define ID_LAYER_SAVEBMP                32627
#define IDM_LAYER_SAVEBMP               32628
#define ID_LAYER_SAVEDISPLAYIMAGEASBMPFILE 32629
#define IDM_DISPLAY_BMPFILE             32630
#define IDM_DISPLAY_SAVEBMP             32631
#define ID_LAYER_SAVEDISPLAYREFERENCEASBMPFILE 32632
#define IDM_REFERENCE_SAVEBMP           32633
#define ID_LAYER_ADDLAYERFROMBINORRAWFILE 32634
#define IDM_BITTOOLS_TEXT2BITSTREAM     32636
#define IDM_BITTOOLS_BINARYIMAGE        32637
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32638
#define _APS_NEXT_CONTROL_VALUE         1228
#define _APS_NEXT_SYMED_VALUE           300
#endif
#endif
